package com.skndan.rdp.entity.constants;

public enum CloudProvider {
  AMAZON_WEB_SERVICE,
  GOOGLE_CLOUD_COMPUTE_ENGINE,
  MICROSOFT_AZURE_VIRTUAL_MACHINES,
  DIGITALOCEAN_DROPLETS,
  LINODE_INSTANCES,
  VULTR_CLOUD_COMPUTE,
  IBM_CLOUD_VIRTUAL_SERVERS,
  ORACLE_CLOUD_INFRASTRUCTURE_COMPUTE,
  HETZNER_CLOUD,
  OVHCLOUD_PUBLIC_CLOUD_INSTANCES,
  ALIBABA_CLOUD_ELASTIC_COMPUTE_SERVICE,
  SCALEWAY_INSTANCES,
  TENCENT_CLOUD_CVM,
  UPCLOUD_SERVERS,
  KAMATERA_CLOUD_SERVERS,
  RACKSPACE_CLOUD_SERVERS;
}
